# -*- coding: utf-8 -*-
"""
Created on Fri Sep 22 16:20:01 2023

@author: mepdw
"""

#Definitions of fieldnames in MFMC

H5_TYPE = "TYPE"
H5_VERSION = "VERSION"
H5_ELEMENT_POSITION = "ELEMENT_POSITION"
H5_ELEMENT_MINOR = "ELEMENT_MINOR"
H5_ELEMENT_MAJOR = "ELEMENT_MAJOR"
H5_ELEMENT_SHAPE = "ELEMENT_SHAPE"
H5_ELEMENT_RADIUS_OF_CURVATURE = "ELEMENT_RADIUS_OF_CURVATURE"
H5_ELEMENT_AXIS_OF_CURVATURE = "ELEMENT_AXIS_OF_CURVATURE"
H5_WEDGE_SURFACE_POINT = "WEDGE_SURFACE_POINT"
H5_WEDGE_SURFACE_NORMAL = "WEDGE_SURFACE_NORMAL"
H5_DEAD_ELEMENT = "DEAD_ELEMENT"
H5_CENTRE_FREQUENCY = "CENTRE_FREQUENCY"
H5_BANDWIDTH = "BANDWIDTH"
H5_PROBE_MANUFACTURER = "PROBE_MANUFACTURER"
H5_PROBE_SERIAL_NUMBER = "PROBE_SERIAL_NUMBER"
H5_PROBE_TAG = "PROBE_TAG"
H5_WEDGE_MANUFACTURER = "WEDGE_MANUFACTURER"
H5_WEDGE_SERIAL_NUMBER = "WEDGE_SERIAL_NUMBER"
H5_WEDGE_TAG = "WEDGE_TAG"
H5_MFMC_DATA = "MFMC_DATA"
H5_MFMC_DATA_IM = "MFMC_DATA_IM"
H5_PROBE_PLACEMENT_INDEX = "PROBE_PLACEMENT_INDEX"
H5_PROBE_POSITION = "PROBE_POSITION"
H5_PROBE_X_DIRECTION = "PROBE_X_DIRECTION"
H5_PROBE_Y_DIRECTION = "PROBE_Y_DIRECTION"
H5_TRANSMIT_LAW = "TRANSMIT_LAW"
H5_RECEIVE_LAW = "RECEIVE_LAW"
H5_PROBE_LIST = "PROBE_LIST"
H5_TIME_STEP = "TIME_STEP"
H5_START_TIME = "START_TIME"
H5_SPECIMEN_VELOCITY = "SPECIMEN_VELOCITY"
H5_WEDGE_VELOCITY = "WEDGE_VELOCITY"
H5_TAG = "TAG"
H5_DAC_CURVE = "DAC_CURVE"
H5_RECEIVER_AMPLIFIER_GAIN = "RECEIVER_AMPLIFIER_GAIN"
H5_FILTER_TYPE = "FILTER_TYPE"
H5_FILTER_PARAMETERS = "FILTER_PARAMETERS"
H5_FILTER_DESCRIPTION = "FILTER_DESCRIPTION"
H5_OPERATOR = "OPERATOR"
H5_DATE_AND_TIME = "DATE_AND_TIME"
H5_PROBE = "PROBE"
H5_SEQUENCE = "SEQUENCE"
H5_LAW = "LAW"
H5_ELEMENT = "ELEMENT"
H5_DELAY = "DELAY"
H5_WEIGHTING = "WEIGHTING"

H5_DEFAULT_PREFIX = {
    H5_PROBE: "P",
    H5_SEQUENCE: "S",
    H5_LAW: "L" }


